# Generated by Django 5.2.3 on 2025-06-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_lignefacture_cout_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
