# Generated by Django 5.2.3 on 2025-06-29 07:21

from django.db import migrations


def remplir_description_vide(apps, schema_editor):
    LigneFacture = apps.get_model('factures', 'LigneFacture')
    LigneFacture.objects.filter(description__isnull=True).update(description='Prestation sans description')


class Migration(migrations.Migration):
    dependencies = [
        ('factures', '0004_lignefacture_description'),
    ]

    operations = [
        migrations.RunPython(remplir_description_vide),
    ]
