# Generated by Django 5.2.3 on 2025-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='fichier_pdf',
        ),
        migrations.AddField(
            model_name='devis',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
