# Generated by Django 5.2.3 on 2025-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_remove_devis_fichier_pdf_devis_pdf_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='envoye',
            field=models.BooleanField(default=False),
        ),
    ]
